---
DEFAULT:
  # These formatting options will be used by default.
  options: "--style=otbs --attach-namespaces --attach-classes --indent=spaces=4 --convert-tabs --align-reference=name --align-pointer=name\
    \ --keep-one-line-statements --pad-header --pad-oper --pad-comma --unpad-paren --max-continuation-indent=120 --max-code-length=120"
